
export const GET_CLUBS = 'GET_CLUBS';
export const GET_CLUBS_START = 'GET_CLUBS_START';
export const GET_CLUBS_SUCCESS = 'GET_CLUBS_SUCCESS';
export const GET_CLUBS_FAIL = 'GET_CLUBS_FAIL';

export const DELETE_CLUB = 'GET_CATEGORIES';
export const DELETE_CLUB_START = 'DELETE_CLUB_START';
export const DELETE_CLUB_SUCCESS = 'DELETE_CLUB_SUCCESS';
export const DELETE_CLUB_FAIL = 'DELETE_CLUB_FAIL';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_START = 'GET_CATEGORIES_START';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';


