//AUTH
export const REGISTER = 'REGISTER';
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN = 'LOGIN';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_START = 'FORGOT_PASSWORD_START';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';

export const IS_LOGGED_CHECK = 'IS_LOGGED_CHECK';
export const IS_LOGGED_CHECK_SUCCESS = 'IS_LOGGED_CHECK_SUCCESS';
export const IS_LOGGED_CHECK_FAIL = 'IS_LOGGED_CHECK_FAIL';

export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAIL = 'GET_USER_DATA_FAIL';

export const EDIT_USER_INFORMATION = 'EDIT_USER_INFORMATION';
export const EDIT_USER_INFORMATION_START = 'EDIT_USER_INFORMATION_START';
export const EDIT_USER_INFORMATION_SUCCESS = 'EDIT_USER_INFORMATION_SUCCESS';
export const EDIT_USER_INFORMATION_FAIL = 'EDIT_USER_INFORMATION_FAIL';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_START = 'CHANGE_PASSWORD_START';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';

export const VERIFY_ACCOUNT = 'VERIFY_ACCOUNT';
export const VERIFY_ACCOUNT_START = 'VERIFY_ACCOUNT_START';
export const VERIFY_ACCOUNT_SUCCESS = 'VERIFY_ACCOUNT_SUCCESS';
export const VERIFY_ACCOUNT_FAIL = 'VERIFY_ACCOUNT_FAIL';

export const RESEND_VERIFY_CODE = 'RESEND_VERIFY_CODE';
export const RESEND_VERIFY_CODE_START = 'RESEND_VERIFY_CODE_START';
export const RESEND_VERIFY_CODE_SUCCESS = 'RESEND_VERIFY_CODE_SUCCESS';
export const RESEND_VERIFY_CODE_FAIL = 'RESEND_VERIFY_CODE_FAIL';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_START = 'RESET_PASSWORD_START';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
