

server:
  servlet:
    context-path: '/'

app:
  api_path: '/api'
  jwtSecret: 'asdfg'
  jwtExpirationInMs: 43200000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/badgateway?allowPublicKeyRetrieval=true&&useSSL=false&serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none

  flyway:
    baseline-on-migrate: false
    enabled: false
    schemas: badgateway

  mail:
    host: smtp.elasticemail.com
    port: 2525
    username: "noreply@spiritsup.com"
    password: "F1CB28C69BEC3C8DDC81326C6A07363C4165"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true